.github/workflows/deploy.yml
.github/workflows/sonar_analysis.yml
.github/workflows/update_infra.yml
CODEOWNERS
README.md
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/generate_openapi.sh
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/bizeventsservice/Application.java
src/main/java/it/gov/pagopa/bizeventsservice/config/LoggingAspect.java
src/main/java/it/gov/pagopa/bizeventsservice/config/MappingsConfiguration.java
src/main/java/it/gov/pagopa/bizeventsservice/config/OpenApiConfig.java
src/main/java/it/gov/pagopa/bizeventsservice/config/RequestFilter.java
src/main/java/it/gov/pagopa/bizeventsservice/config/ResponseValidator.java
src/main/java/it/gov/pagopa/bizeventsservice/config/WebMvcConfiguration.java
src/main/java/it/gov/pagopa/bizeventsservice/controller/HomeController.java
src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
src/main/java/it/gov/pagopa/bizeventsservice/exception/AppException.java
src/main/java/it/gov/pagopa/bizeventsservice/exception/ErrorHandler.java
src/main/java/it/gov/pagopa/bizeventsservice/model/AppCorsConfiguration.java
src/main/java/it/gov/pagopa/bizeventsservice/model/AppInfo.java
src/main/java/it/gov/pagopa/bizeventsservice/model/ProblemJson.java
src/main/java/it/gov/pagopa/bizeventsservice/util/Constants.java
src/main/resources/application-local.properties
src/test/java/it/gov/pagopa/bizeventsservice/ApplicationTest.java

feat: [PPR-48] Initial configuration

---

helm/values-prod.yaml
helm/values-uat.yaml

- Config helm files with proper value of env config, env secret variables and liveness probe

Feat: [PPR-497] config uat and prod helm files

---

CODEOWNERS

Update code owners with a dedicated team

Update project code owners

---

.devops/deploy-pipelines.yml

chore: update deploy pipeline

---

.devops/performance-test-pipelines.yml
performance-test/docker-compose.yaml
performance-test/run_performance_test.sh
performance-test/src/dev.environment.json
performance-test/src/uat.environment.json

This PR involve the refinement of the performance test pipeline (from dedicated template present in [microservise-template](https://github.com/pagopa/template-java-spring-microservice)) by editing bash script `run_performace_test.sh`, configuration files `*.environment.json`, and statements contained in `performance-test-pipeline.yml`

ci: performance-test-pipeline refinement

---

src/main/java/it/gov/pagopa/bizeventsservice/entity/BizEvent.java
src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertBizEventEntityToCtReceiptModelResponse.java
src/main/java/it/gov/pagopa/bizeventsservice/model/response/enumeration/StatusType.java
src/test/java/it/gov/pagopa/bizeventsservice/service/BizEventsServiceTest.java
src/test/resources/biz-events/bizEvent.json
src/test/resources/biz-events/bizEvent_duplicate.json

fix mapping on real biz event v2

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml
src/main/java/it/gov/pagopa/bizeventsservice/entity/BizEvent.java
src/main/java/it/gov/pagopa/bizeventsservice/entity/Transfer.java
src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertBizEventEntityToCtReceiptModelResponse.java
src/main/java/it/gov/pagopa/bizeventsservice/model/response/CtReceiptModelResponse.java
src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsRepository.java
src/test/java/it/gov/pagopa/bizeventsservice/service/BizEventsServiceTest.java
src/test/resources/biz-events/bizEvent.json
src/test/resources/biz-events/bizEvent_duplicate.json

fix_data: manage date format

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml

prod deploy

---

openapi/openapi.json

openapi.json - mbdAttachment not required
mbdAttachment field has to be declared not required in order to allow client side response validation

fix - mbdAttacchment not required

---

.devops/deploy-pipelines.yml

fix: Add KubectlInstaller

---

CODEOWNERS
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml

fix: Update elastic secret [PAGOPA-1196]

---

.github/workflows/code_review.yml
.github/workflows/update_code.yml
Dockerfile
README.md
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
pom.xml

Changes necessary to move the microservie to java 17
This change is needed becuase java 11 is deprecated

PAGOPA-1454 moving to java 17

---

src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertBizEventListToTransactionDetailResponse.java
src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java

introducing changes to subject recovery for transaction using biz-event data (avoid generic remittance info)

[PRDP-335] feat: Add checks on remittance info

---

openapi/openapi.json
src/main/java/it/gov/pagopa/bizeventsservice/controller/IBizEventController.java
src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/TransactionController.java
src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java

- updated APIs definition
- updated openapi
Reviewed openapi to match product definition and to match documentation https://pagopa.atlassian.net/wiki/spaces/PPR/pages/872218824/Design+Review+Lista+Transazioni

[PRDP-356] chore: Review openapi spec generation biz service

---

src/test/java/it/gov/pagopa/bizeventsservice/controller/TransactionControllerTest.java

- Fix unit tests transactionController

[fix] Fix unit tests transactionController

---

openapi/generate_openapi.sh
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
src/main/java/it/gov/pagopa/bizeventsservice/config/OpenApiConfig.java
src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
src/main/resources/application.properties
src/test/java/it/gov/pagopa/bizeventsservice/OpenApiGenerationTest.java
src/test/resources/application.properties

- added `openapi`,  `openapi_helpdesk`,  `openapi_ec`,  `openapi_io`
- added class for openapi file generation
Add product specific openapi file

[PRDP-356] feat: Updated openapi

---

integration-test/src/config/.env.dev
integration-test/src/config/.env.local
integration-test/src/config/.env.uat
integration-test/src/features/organizationsreceipt.feature
integration-test/src/step_definitions/support/biz_events_cosmosdb_client.js
integration-test/src/step_definitions/support/bizeventservice_client.js
integration-test/src/step_definitions/support/common.js
integration-test/src/step_definitions/support/organizationsreceipt_steps.js
src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewGeneral.java
src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewUser.java
src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewCartRepository.java
src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewGeneralRepository.java
src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewUserRepository.java
src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java

- Reworked integration test 
- Introduces DisabledAPI test
- Fixed various bug
- Added isPayer property to ViewUser to verify if the user requesting the transaction is debtor or payer
[Issue PRDP-363](https://pagopa.atlassian.net/browse/PRDP-363?atlOrigin=eyJpIjoiMjdlNGExZTM3ODEyNGMzOGEzYzBiY2I2MmVlMjA2OTAiLCJwIjoiaiJ9)

[PRDP-363] Reworked integration tests

---

src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java

- Remove taxCode validity check

fix: Remove taxCode validity check

---

integration-test/src/config/.env.dev
integration-test/src/config/.env.local
integration-test/src/config/.env.uat
integration-test/src/step_definitions/support/bizeventservice_client.js

chore: Fix integ test

---

openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java
src/main/resources/application.properties
src/test/resources/application.properties

- fix `/transactions` response schema
- fix `/transactions/{transaction-id}` response schema
- set `/transactions` `size` query parameter default value to `10`

reviewed openapi

---

.github/workflows/integration_test.yml
.gitignore
.identity/00_data.tf
.identity/03_github_environment.tf

chore: Fix slack notify

---

openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
src/main/resources/application.properties
src/test/resources/application.properties

chore: Disable springdoc use-fqn

---

openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
pom.xml

Updating openapis
Update needed to put a value inside openapi title and description
Manually

PAGOPA-1681 adding testResources in pom.xml file

---

src/main/java/it/gov/pagopa/bizeventsservice/entity/DebtorPosition.java
src/main/java/it/gov/pagopa/bizeventsservice/model/response/enumeration/UserType.java

Adding new fields to transactionDetails user enum and debtorPosition
This addition is needed to map properly the values inserted by eCommerce
Manually

PAGOPA-1724 adding missing fields

---

openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
openapi/openapi_io_patch.json
src/main/java/it/gov/pagopa/bizeventsservice/config/OpenApiConfig.java
src/main/java/it/gov/pagopa/bizeventsservice/controller/ITransactionController.java

chore: Patch IO api

---

openapi/openapi_io_patch.json

chore: Remove pdf for io

---

openapi/openapi_io_patch.json

chore: Re-add pdf to IO

---

src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java

- changed isDebtor value logic: check if the cart contains an item in which the user is a debtor --> isDebtor = true
- business rule

[PAGOPA-1748] check cart items in which the user is debtor

---

.github/workflows/deploy_with_github_runner.yml

chore: Add self_hosted_runner_image_tag

---

openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
openapi/openapi_io_patch.json

chore: Upd openapi

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
openapi/openapi_io_patch.json
pom.xml
src/main/java/it/gov/pagopa/bizeventsservice/entity/view/UserDetail.java

bug: [fix-io-payer]: fixed payer null

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
openapi/openapi_io_patch.json
pom.xml
src/main/java/it/gov/pagopa/bizeventsservice/model/response/enumeration/UserType.java

bug: [fix-user-type] added REGISTERED type

---

.github/workflows/report_ingestion.yml
.gitignore
.identity/00_data.tf
.identity/03_github_environment.tf
report/run.sh
report/src/README.md
report/src/config/.env.local
report/src/package.json
report/src/utils/report.js
report/src/utils/utils.js

chore: Biz ingestion report

---

src/main/java/it/gov/pagopa/bizeventsservice/model/response/Debtor.java
src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java

- removed cart merge
- business request
- manual test

feat: [PAGOPA-2070] - remove cart merge

---

integration-test/src/package-lock.json
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
openapi/openapi_io_patch_lap.json
report/src/package-lock.json
src/main/resources/application.properties
src/test/resources/application.properties

chore: Upd IO LAP patch openapi

---

.github/workflows/code_review.yml
.github/workflows/integration_test.yml
docker/run_docker.sh
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
integration-test/src/config/.env.dev
integration-test/src/config/.env.local
integration-test/src/config/.env.uat
integration-test/src/step_definitions/support/bizeventservice_client.js
integration-test/src/step_definitions/support/common.js
integration-test/src/step_definitions/support/organizationsreceipt_steps.js
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
openapi/openapi_io_patch.json
openapi/openapi_io_patch_lap.json
pom.xml
src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java

updated integration test for:
- paid notices list
- paid notice detail
- disable paid notice
- changed API path 
- local env test

feat: [PagoPA-2083] Api integration test

---

src/main/java/it/gov/pagopa/bizeventsservice/entity/view/BizEventsViewGeneral.java
src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java
src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java

- fixed id value
- fixed payeeName e payeeTaxCode value
- fixed amount value
- fixed junit tests
- error reporting by users of the service

bug: [PagoPa-2166] - fix list info for cart

---

src/main/java/it/gov/pagopa/bizeventsservice/controller/impl/PaidNoticeController.java
src/main/java/it/gov/pagopa/bizeventsservice/exception/AppError.java
src/main/java/it/gov/pagopa/bizeventsservice/repository/BizEventsViewUserRepository.java
src/main/java/it/gov/pagopa/bizeventsservice/service/ITransactionService.java
src/main/java/it/gov/pagopa/bizeventsservice/service/impl/TransactionService.java
src/test/java/it/gov/pagopa/bizeventsservice/controller/PaidNoticeControllerTest.java
src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java

- managed recovery via event-id
- error while retrieving the detail of a cart event
- manual and junit tests

BUG: [PAGOPA-2260] - issue cart

---

openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_io.json
src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertBizEventEntityToCtReceiptModelResponse.java
src/main/java/it/gov/pagopa/bizeventsservice/model/response/CtReceiptModelResponse.java
src/test/resources/receipts/getOrganizationReceipt.json

- Change the type of the paymentDateTime field from date to date-time
In the XSD definition, the paymentDateTime field is of the date-time type. Therefore, the bizEvent field must align with the corresponding field's definition in the XSD.
Unit test

[MAIN-12] change type format for paymentDateTime field

---

.github/workflows/integration_test.yml
.identity/00_data.tf
.identity/03_github_environment.tf
.identity/99_main.tf
integration-test/src/config/.env.local
integration-test/src/features/organizationsreceipt.feature
integration-test/src/step_definitions/support/biz_events_cosmosdb_client.js
integration-test/src/step_definitions/support/bizeventservice_client.js
integration-test/src/step_definitions/support/common.js
integration-test/src/step_definitions/support/cosmosdb_client.js
integration-test/src/step_definitions/support/organizationsreceipt_steps.js

- added missing subkey secret
- removed useless step from integration test GHA
- removed deprecated test use case
- fixed integration test
**_Before merge_** `apply .identity`:
[PIDM-201](https://pagopa.atlassian.net/browse/PIDM-201)
[PIDM-201]: https://pagopa.atlassian.net/browse/PIDM-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PIDM-201] fix: Integration test

---

.github/workflows/code_review.yml
.opex/biz-service/env/prod/config.yaml
.opex/biz-service/env/prod/terraform.tfvars

- updated opex config
- fix backend var
- bump code-review gha version

fix: Dashboard opex

---

.github/workflows/code_review.yml

- Updated deprecated `ubuntu-20.04` references to `ubuntu-22.04` in workflow files
- Modified GitHub Actions and Azure Pipeline configurations
This change is required because `ubuntu-20.04` will be fully deprecated on April 1st, 2025. Without this update, workflows will fail after that date.
GitHub Actions and Azure DevOps are both retiring this image:
- GitHub Actions: https://github.com/actions/runner-images/issues/11101
- Azure DevOps: https://devblogs.microsoft.com/azure-devops/upcoming-updates-for-azure-pipelines-agents-images/

fix: [PIDM-381] update deprecated ubuntu-20.04

---

.github/workflows/code_review.yml
.github/workflows/create_dashboard.yaml
.github/workflows/deploy_with_github_runner.yml
.github/workflows/integration_test.yml
.github/workflows/release_deploy.yml
.github/workflows/report_ingestion.yml
.identity/.terraform.lock.hcl
.identity/00_data.tf
.identity/03_github_environment.tf
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_lap.json
openapi/openapi_lap_jwt.json
openapi/openapi_transaction.json
openapi/openapi_transaction_jwt.json
pom.xml

- Implemented workload identity
- Updated GHA release&deploy with new runner
- Added replicas to helm
[PIDM-488](https://pagopa.atlassian.net/browse/PIDM-488)
[PIDM-491]: https://pagopa.atlassian.net/browse/PIDM-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIDM-488]: https://pagopa.atlassian.net/browse/PIDM-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [PIDM-488] Implement workload identity

---

.identity/00_data.tf
.identity/03_github_environment.tf
.identity/99_variables.tf

chore: Upd en github repo

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_lap.json
openapi/openapi_lap_jwt.json
openapi/openapi_transaction.json
openapi/openapi_transaction_jwt.json
pom.xml
src/main/java/it/gov/pagopa/bizeventsservice/mapper/ConvertViewsToTransactionDetailResponse.java

- fixed UTC behavior [see here](https://pagopa.atlassian.net/browse/PIDM-353)
- incorrect display of payment time
- manual and junit test

bug: [PIDM-353] incorrect time

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_lap.json
openapi/openapi_lap_jwt.json
openapi/openapi_transaction.json
openapi/openapi_transaction_jwt.json
pom.xml
src/main/resources/application.properties

- set `responseContinuationTokenLimitInKb` to `1Kb` to prevent header limit errors
Avoid HeadersTooLargeException
[PIDM-610](https://pagopa.atlassian.net/browse/PIDM-610)
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/azure-spring-data-cosmos#setup-configuration-class
[PIDM-610]: https://pagopa.atlassian.net/browse/PIDM-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PIDM-610] fix: Header limit errors

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
openapi/openapi.json
openapi/openapi_ec.json
openapi/openapi_helpdesk.json
openapi/openapi_lap.json
openapi/openapi_lap_jwt.json
openapi/openapi_transaction.json
openapi/openapi_transaction_jwt.json
pom.xml
src/main/java/it/gov/pagopa/bizeventsservice/entity/view/enumeration/OriginType.java
src/main/resources/application.properties
src/test/java/it/gov/pagopa/bizeventsservice/service/TransactionServiceTest.java
src/test/java/it/gov/pagopa/bizeventsservice/util/ViewGenerator.java

related to [pagopa-biz-events-datastore](https://github.com/pagopa/pagopa-biz-events-datastore/pull/101)
- added NDP004PROD management
- new serviceIdentifier value

chore: [PAGOPA-3124] - NDP004PROD

---

helm/values-prod.yaml

- increased maxReplica to `20` in `PROD` environment
[PIDM-1038](https://pagopa.atlassian.net/browse/PIDM-1038)
Allow service to scale properly in case of high load
[PIDM-1038]: https://pagopa.atlassian.net/browse/PIDM-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PIDM-1038] chore: Increase maxReplica in PROD
